name: Pyright

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  pyright:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        shell: bash
        run: |
          git init .
          git remote add origin "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          git fetch --no-tags --depth=1 origin "${GITHUB_SHA}"
          git checkout --detach FETCH_HEAD

      - name: Install development dependencies
        run: python3 -m pip install -r requirements-dev.txt

      - name: Run Pyright
        run: python3 -m pyright
